# ==========================================================================
# CRE PROJECT SETTINGS FILE — PrivateSignal
# ==========================================================================
default: &default
  cre-cli:
    don-family: "zone-a"
  rpcs:
    - chain-name: "ethereum-testnet-sepolia"
      url: ${ETH_SEPOLIA_RPC_URL}
    - chain-name: "ethereum-testnet-sepolia-base-1"
      url: ${BASE_SEPOLIA_RPC_URL}

local-simulation: *default

staging-settings: *default

production-settings:
  cre-cli:
    don-family: "zone-a"
  rpcs:
    - chain-name: "ethereum-mainnet"
      url: ${ETH_MAINNET_RPC_URL}
    - chain-name: "ethereum-mainnet-base-1"
      url: ${BASE_MAINNET_RPC_URL}
